baseurl = "https://amiiy.github.io"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "cactus"

[params]
    colortheme = "dark" 
    description = "Im software engineer with more focus on the back-end!"
    mainSection = "posts"
    postsOnHomePage = 5


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4