baseurl = "https://amiiy.github.io"
languageCode = 'en-us'
title = '... Amiy ...'
theme = "cactus"

[params]
    colortheme = "dark" 
    description = "yet another software engineer with more focus on the back-end! this blog is just a note taking application for me! all the information here could be wrong! please DYOR"
    mainSection = "posts"
    postsOnHomePage = 5


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4